# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent', models.TextField(blank=True, default='', max_length=255)),
                ('image', models.ImageField(blank=True, max_length=255, upload_to='posts')),
                ('webm', models.TextField(blank=True, default='', max_length=255)),
                ('mp4', models.TextField(blank=True, default='', max_length=255)),
                ('lang', models.IntegerField(choices=[(1, 'English'), (2, 'Vietnamese')], default=1)),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
