# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
    ]
